import Layout from "@/components/Layout/Layout"
import "./globals.css"
import type { Metadata } from "next"
//import { AuthContextProvider } from "@/context/AuthContext"

export const metadata: Metadata = {
  title: "FCC",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout>
        {/* <AuthContextProvider>
          <Layout>{children}</Layout>
        </AuthContextProvider> */}
      </body>
    </html>
  )
}
